### PR TITLE
Update project.clj

### PR DESCRIPTION
**Pull request by andrewsuzuki**
Update cljs-time to 0.5.0-alpha1 for fix to andrewmcveigh/cljs-time#57

### CODE REVIEW

**Comment by dijonkitchen** [comment]
Any update on this? I think it's breaking Heroku deployment as well.

**Comment by Gregg8** [comment]
All you need to do is bump the `project.clj` of YOUR application to `0.5.0-alpha1` and that will be the version of `cljs-time` used for your app (and all libs).

**Comment by dijonkitchen** [comment]
I'm actually using re-com with a [re-frame-template](/Day8/re-frame-template). How would you override it if my re-frame template is using re-com 0.8.3?

**Comment by Gregg8** [comment]
That template produces a `project.clj` for your app. All you need to do is add `[com.andrewmcveigh/cljs-time "0.5.0-alpha1"]` in the `:dependencies` of that `project.clj` and you're good to go.

**Comment by dijonkitchen** [comment]
FWIW, I did this but it still doesn't work.

**Comment by blak3mill3r** [comment]
@dijonkitchen Check `lein deps :tree` to see what version of `cljs-time` your project is using. If some other package is pulling in some other version of it, you can use leiningen `:exclusions` on *that* dependency to "fix" it. https://github.com/technomancy/leiningen/blob/master/doc/FAQ.md

**Comment by Gregg8** [comment]
We're not too keen on bumping the `cljs-time` dep until it's released properly. 

If this issue hasn't been resolved for you, please share your `lein deps :tree` results.

Closing this for now, but can reopen if necessary.

**Pull request closed without merging**
