### PR TITLE
Visual feeback when clicking on buttons

### PR DESCRIPTION
**Pull request by Frozenlock**
Clicking on buttons should provide a visual feedback to let the user know he correctly clicked the element.

Buttons without feedback don't *feel* right.

### CODE REVIEW

**Comment by Gregg8** [comment]
I tested this but could not get it working in Chrome or Firefox. In Chrome DevTools, I could turn on the active state and see what it is supposed to look like, but actually pressing the button down did not show this state. Note that the button is implemented as a [:div] so I tried changing it to [:button] and it still didn't show, but that has different default styling so the icons were not aligned properly, so I left this one for now. Comments? Modified PR?

**Comment by Gregg8** [comment]
Is this still an issue? I've left this open because of my above comment.

**Comment by Gregg8** [comment]
I know it's been a long time, but if this is still an issue, please refer to my original comment, otherwise I'll close this shortly.

**Comment by Frozenlock** [comment]
You're right, the `div` doesn't appear to get the `active` pseudo-class.
I can't remember what I did around this.

I'll close the PR, but the initial criticism still stands; those round buttons feel weird.

**Pull request closed without merging**
