### PR TITLE
Allow for custom background and tooltip styles

### PR DESCRIPTION
**Pull request by StephenCharles**
I needed to change the popover tooltip background and decrease the font size of the tooltip. Not sure if this goes against re-com's philosophy as it moves it further away from bootstrap styles.

### CODE REVIEW

**Comment by Gregg8** [comment]
Thanks for your PR. Will be getting back into re-com shortly so will go through your changes in more detail at that point to determine the best way to handle this.

**Comment by StephenCharles** [comment]
Sounds good.

**Comment by mike-thompson-day8** [comment]
So, everyone's needs and tastes are different and, as a result, everyone wants a different style. This will incrementally lead us towards components which have an endless number of named args.  We have to resist that.  

I'd prefer to handle all possible style changes in one go, by adding a single `style` arg for each particular element of the component. 

With the above in mind,  I'm happy to add  `tooltip-style` but I'd prefer to not add `popover-color`.  

Instead of `popover-color`  I'd prefer to add a style which covers the popover part, allowing you to modify the popover colour.  In effect, we want to allow the popover colour to be changed, but we want to do it in a general way (via `:style` on that part) rather than by a specific new named arg.

**Comment by StephenCharles** [comment]
Great point, I'll make changes accordingly. Thanks for getting back to me!

**Comment by StephenCharles** [comment]
@mike-thompson-day8 let me know what you think. I believe I did what you asked.

**Comment by StephenCharles** [comment]
Just upped to the most recent version and I have no more use for this update. Thanks for all your hard work :)

**Pull request closed without merging**
