### PR TITLE
Fix :id-fn and :label-fn in dropdown component

### PR DESCRIPTION
**Pull request by meowcakes**
:id-fn and :label-fn do not work when displaying the currently selected value on the dropdown button, as it is still using the hard-coded keywords :id and :label elsewhere.

Also, the validation function should be ifn?, not fn?, so that you can use e.g. a keyword as the id-fn.

Not sure how you will feel about the changes I've made to item-for-id, etc., in utils, as it is no longer really an "id" function but now a much more generic "find this thing in a sequence using this mapping function" function, although the name implies otherwise.

### CODE REVIEW

**Comment by meowcakes** [comment]
There's still use of hard-coded keywords in choices-with-group-headings, not sure how you would like to fix that one.

**Comment by Gregg8** [comment]
Many thanks for your pull request. Clearly there was more work to be done on that dropdown change. I have incorporated your changes into my develop branch. 

My comments:
 - `ifn?` suggestions are good.
 - I have left the names of the `item-for-id` etc. functions unchanged as they are still dealing with what in a re-com sense, is an id. It's just that the id can be anything now.

 - re `choices-with-group-headings`, I have not determined the best solution for that one as yet, but worked out what problem it causes. Once that's sorted, I'll push out a new re-com.

**Comment by Gregg8** [comment]
Update: The bug I thought I was chasing for `choices-with-group-headings` was in fact for a different bug. `move-to-new-choice` needed to be passed `id-fn` so it could then pass it on to `position-for-id`. To symptom was that the up, down, home, end keys didn’t work when. Now they do.

Regarding `choices-with-group-headings`, my conclusion is that this doesn't need to be changed, at least for the use cases I tested it for. All this is doing is returning the original choices vector with extra entries inserted for the headings. If you can find a use case where this will cause a problem let me know.

**Comment by meowcakes** [comment]
Cool, thanks!

From what I can tell `choices-with-group-headings` ceases to function correctly when a custom `group-fn` is used, for example:
```clojure
[single-dropdown
 :width "250px"
 :choices [{:id 1 :label "one" :groupp "foo"}
           {:id 2 :label "two" :groupp "foo"}
           {:id 3 :label "three" :groupp "foo"}
           {:id 4 :label "four" :groupp "bar"}
           {:id 5 :label "five" :groupp "bar"}
           {:id 6 :label "six" :groupp "bar"}
           {:id 7 :label "seven" :groupp "baz"}
           {:id 8 :label "eight" :groupp "baz"}
           {:id 9 :label "nine" :groupp "baz"}]
 :on-change (fn [_] true)
 :group-fn :groupp
 :model (atom 9)]
```

It also stops working when a custom `id-fn` is used:
```clojure
[single-dropdown
 :width "250px"
 :choices [{:idd 1 :label "one" :group "foo"}
           {:idd 2 :label "two" :group "foo"}
           {:idd 3 :label "three" :group "foo"}
           {:idd 4 :label "four" :group "bar"}
           {:idd 5 :label "five" :group "bar"}
           {:idd 6 :label "six" :group "bar"}
           {:idd 7 :label "seven" :group "baz"}
           {:idd 8 :label "eight" :group "baz"}
           {:idd 9 :label "nine" :group "baz"}]
 :on-change (fn [_] true)
 :id-fn :idd
 :model (atom 9)]
```

**Comment by Gregg8** [comment]
Thanks for those examples. They should now work in release [0.5.4](https://github.com/Day8/re-com/releases/tag/0.5.4)

**Comment by meowcakes** [comment]
Thanks!

**Comment by Gregg8** [comment]
Can this be closed now?

**Comment by meowcakes** [comment]
Yes, sorry for the late reply.

**Pull request closed without merging**
